/**
 * Complete End-to-End Test:
 * 1. Generate REAL certificate image with OpenAI
 * 2. Upload to REAL IPFS via Storacha
 * 3. Create and upload NFT metadata
 */

import 'dotenv/config'
import { generateCertificateImage } from './src/services/nft-image'
import { uploadImageToIPFS, uploadMetadataToIPFS, getStorageStatus } from './src/services/storage-simple'
import fs from 'fs/promises'

const testBond = {
  id: `bond_real_${Date.now()}`,
  issuer: 'ARC Finance',
  series: 'Q4 2025',
  principal: '1000',
  currency: 'USDC',
  coupon: '5',
  tenor: '90',
  issueDate: '2025-11-15',
  maturityDate: '2026-02-13'
}

async function testFullCertificate() {
  console.log('\n╔═══════════════════════════════════════════════════════════╗')
  console.log('║  🎨 COMPLETE NFT CERTIFICATE GENERATION & UPLOAD         ║')
  console.log('╚═══════════════════════════════════════════════════════════╝\n')

  // Step 1: Check storage
  console.log('📊 Step 1: Checking Storage Status...')
  const storageStatus = await getStorageStatus()
  console.log('   Provider:', storageStatus.provider)
  console.log('   Working:', storageStatus.working ? '✅ Yes' : '❌ No')
  
  if (!storageStatus.working) {
    console.log('\n⚠️  Storacha CLI not available - will use mock storage')
    console.log('   To enable real IPFS: storacha login your-email@example.com\n')
  }

  // Step 2: Generate certificate with OpenAI
  console.log('\n🎨 Step 2: Generating Certificate Image with OpenAI...')
  console.log('   Bond ID:', testBond.id)
  console.log('   Style: Institutional')
  console.log('   ⏳ Calling OpenAI GPT-Image (takes 10-30 seconds)...\n')

  const imageResult = await generateCertificateImage({
    context: 'bond_certificate',
    style: 'institutional',
    bond_id: testBond.id,
    fields: {
      title: `${testBond.issuer} — Bond Certificate`,
      series_label: testBond.series,
      principal_label: `${testBond.principal} ${testBond.currency}`,
      coupon_label: `${testBond.coupon}%`,
      tenor_label: `${testBond.tenor} Days`,
      issuer_display_name: testBond.issuer,
      transferability: 'Soulbound',
      issue_date: testBond.issueDate,
      maturity_date: testBond.maturityDate
    }
  })

  if (imageResult.status === 'failed') {
    console.log('   ❌ OpenAI generation failed:', imageResult.error)
    return
  }

  console.log('   ✅ Image generated by OpenAI!')
  console.log('   Image ID:', imageResult.image_id)
  console.log('   Size:', (imageResult.image_base64.length * 0.75 / 1024 / 1024).toFixed(2), 'MB')
  
  // Save locally for inspection
  const localPath = `/tmp/${testBond.id}-certificate.png`
  const imageBuffer = Buffer.from(imageResult.image_base64, 'base64')
  await fs.writeFile(localPath, imageBuffer)
  console.log('   💾 Saved locally:', localPath)

  // Step 3: Upload image to IPFS
  console.log('\n📤 Step 3: Uploading Certificate to IPFS via Storacha...')
  const ipfsImageResult = await uploadImageToIPFS({
    bondId: testBond.id,
    buffer: imageBuffer,
    filename: `${testBond.id}-certificate.png`,
    contentType: 'image/png'
  })

  console.log('   ✅ Certificate uploaded!')
  console.log('   Storage Type:', ipfsImageResult.storage_type === 'ipfs' ? '🌍 Real IPFS' : '⏸️  Mock Storage')
  console.log('   CID:', ipfsImageResult.cid)
  console.log('   IPFS URL:', ipfsImageResult.ipfs_url)
  console.log('   Gateway:', ipfsImageResult.gateway_url)

  // Step 4: Create NFT metadata
  console.log('\n📋 Step 4: Creating NFT Metadata...')
  const nftMetadata = {
    name: `${testBond.issuer} Bond — ${testBond.series}`,
    description: `A ${testBond.tenor}-day ARC bond paying ${testBond.coupon}% coupon, principal ${testBond.principal} ${testBond.currency}, settled on ARC Network. Certificate generated by OpenAI, stored on IPFS.`,
    image: ipfsImageResult.ipfs_url,
    external_url: `https://app.arcfx.finance/bonds/${testBond.id}`,
    attributes: [
      { trait_type: 'Bond ID', value: testBond.id },
      { trait_type: 'Series', value: testBond.series },
      { trait_type: 'Principal', value: `${testBond.principal} ${testBond.currency}` },
      { trait_type: 'Currency', value: testBond.currency },
      { trait_type: 'Coupon Rate', value: `${testBond.coupon}%` },
      { trait_type: 'Tenor', value: `${testBond.tenor} Days` },
      { trait_type: 'Issuer', value: testBond.issuer },
      { trait_type: 'Transferability', value: 'Soulbound' },
      { trait_type: 'Issue Date', value: testBond.issueDate },
      { trait_type: 'Maturity Date', value: testBond.maturityDate },
      { trait_type: 'Network', value: 'ARC Testnet' },
      { trait_type: 'Generated By', value: 'OpenAI GPT-Image' },
      { trait_type: 'Storage', value: ipfsImageResult.storage_type }
    ]
  }

  console.log('   ✅ Metadata created')
  console.log('   Attributes:', nftMetadata.attributes.length)

  // Step 5: Upload metadata
  console.log('\n📤 Step 5: Uploading Metadata to IPFS...')
  const ipfsMetadataResult = await uploadMetadataToIPFS({
    metadata: nftMetadata,
    filename: `${testBond.id}-metadata.json`
  })

  console.log('   ✅ Metadata uploaded!')
  console.log('   Storage Type:', ipfsMetadataResult.storage_type === 'ipfs' ? '🌍 Real IPFS' : '⏸️  Mock Storage')
  console.log('   CID:', ipfsMetadataResult.cid)
  console.log('   Gateway:', ipfsMetadataResult.gateway_url)

  // Results
  console.log('\n╔═══════════════════════════════════════════════════════════╗')
  console.log('║  ✅ COMPLETE SUCCESS!                                    ║')
  console.log('╚═══════════════════════════════════════════════════════════╝')

  console.log('\n📦 Bond Certificate Package:\n')
  console.log('   Bond ID:', testBond.id)
  console.log('   Issuer:', testBond.issuer)
  console.log('   Principal:', `${testBond.principal} ${testBond.currency}`)
  console.log('   Coupon:', `${testBond.coupon}%`)

  console.log('\n🖼️  OpenAI Generated Certificate:\n')
  console.log('   ✅ Generated by OpenAI GPT-Image')
  console.log('   💾 Saved to:', localPath)
  console.log('   🌍 IPFS CID:', ipfsImageResult.cid)
  console.log('   🔗 View at:', ipfsImageResult.gateway_url)

  console.log('\n📋 NFT Metadata:\n')
  console.log('   🌍 IPFS CID:', ipfsMetadataResult.cid)
  console.log('   🔗 View at:', ipfsMetadataResult.gateway_url)

  console.log('\n🔗 For Smart Contract:\n')
  console.log('   tokenURI() should return:', ipfsMetadataResult.ipfs_url)

  console.log('\n💾 For Database:\n')
  console.log(`   INSERT INTO bond_nft_images VALUES (`)
  console.log(`     '${testBond.id}',`)
  console.log(`     'institutional',`)
  console.log(`     '${ipfsImageResult.cid}',`)
  console.log(`     '${ipfsImageResult.ipfs_url}',`)
  console.log(`     '${ipfsImageResult.gateway_url}',`)
  console.log(`     '${ipfsImageResult.storage_type}',`)
  console.log(`     NOW()`)
  console.log(`   );\n`)

  if (ipfsImageResult.storage_type === 'ipfs') {
    console.log('🎉 YOUR REAL NFT CERTIFICATE IS ON IPFS!')
    console.log('   Check Storacha console: https://console.storacha.network/')
    console.log('   View certificate: ' + ipfsImageResult.gateway_url)
    console.log('   View metadata: ' + ipfsMetadataResult.gateway_url)
  } else {
    console.log('⏸️  Using mock storage (Storacha CLI not available)')
    console.log('   But OpenAI image generation worked!')
    console.log('   View local file: open ' + localPath)
  }

  console.log('\n✨ NFT Certificate Generation System: FULLY OPERATIONAL!\n')
}

testFullCertificate().catch(err => {
  console.error('\n❌ Test Failed:', err.message)
  console.error(err)
  process.exit(1)
})

